config/routes.rb
Ritly::Application.routes.draw do
  
  resources :users, :sessions

  root to: 'ritly#index'

  get '/go/:random_string/preview', to: 'ritly#preview', as: :preview

  get '/go/:random_string', to: 'ritly#go', as: :go

  get '/ritly/:id/show', to: 'ritly#show', as: :show

  post '/ritly', to: 'ritly#create', as: :create 


  get '/signup' => 'users#new'
  
  match '/signout', to: 'sessions#destroy', via: :delete
  
  get'/signin' => 'sessions#new'


end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception
end

app/controllers/ritly_controller.rb
class RitlyController < ApplicationController
	before_filter :signed_in_user, only: [:create, :show, :go, :preview]

	def index
	end

	def create
		new_ritly = params.require(:ritly).permit(:link)
		if new_ritly["link"][0] != 'h'
			new_ritly["link"] = "http://" + new_ritly["link"]
		end
		ritly = Url.find_by(link: new_ritly["link"])
		if ritly == nil
			new_ritly['random_string'] = SecureRandom.urlsafe_base64(10)
			ritly = Url.create(new_ritly)
		end
		redirect_to show_path(ritly)
	end

	def show
		id = params[:id]
		@ritly = Url.find(id)
	end

	def go
		random_string = params[:random_string]
		ritly = Url.find_by(random_string: random_string)
		redirect_to ritly[:link]
	end

	def preview
		random_string = params[:random_string]
		@ritly = Url.find_by(random_string: random_string)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ritly_helper.rb
module RitlyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<%= render 'layouts/header' %>

	<section>
	  <div class="row-fluid">

	    <div class="span10">
	      <%flash.each do|key,value|%>
	              <div class="alert alert-<%=key%>"> <%=value%> </div>
	      <%end%>
	      <%= yield %>
	    </div>
	    <%= debug(params) if Rails.env.development? %>
	    <%= debug(session) if Rails.env.development? %>
	  </div>
	</section>

</div>
</body>
</html>

app/views/ritly/_ritly_output.html.erb
<p>Your original URL was: <%= @ritly.link %>.</p>
<p>Your code is: <%= @ritly.random_string %>.</p>


<p>Go to <a href='http://localhost:3000/go/<%=@ritly.random_string %>'>localhost:3000/go/<%=@ritly.random_string %></a> to visit your URL.</p>

app/views/ritly/index.html.erb
<div class="entry_box">

		<h1>RITLY</h1>
		<p>From the creators of Edward Scissorhands comes RITLY, a URL shortner.</p> 
		<%= form_for :ritly, url: create_path, method: :post do |f| %>
		  <p>
		    <%= f.text_field :link, placeholder: "Enter URL to shorten" %>
		  </p>
		 
		  <p>
		    <%= f.submit %>
		  </p>
		<% end %>

</div>
 

app/views/ritly/preview.html.erb
<div class="entry_box">
	<h1>RITLY</h1>
	<%= render  partial: "ritly_output" %>
	<img src="http://api1.thumbalizr.com/?url=<%=@ritly.link%>&width=300&api_key=736845a7733392d44669e17527f0a9b1"  />

	<p><%= link_to 'Back to home', root_path %></p>
</div>

app/views/ritly/show.html.erb
<div class = "entry_box">
	<h1>RITLY</h1>
	<%= render  partial: "ritly_output" %>

	<%= link_to 'Back to home', root_path %>
</div>